---
title: "Your Title"
subtitle: "BMIN503/EPID600 Final Project"
author: "Ziwei Pan"
format: html
editor: visual
number-sections: true
embed-resources: true
---

------------------------------------------------------------------------

Use this template to complete your project throughout the course. Your Final Project presentation will be based on the contents of this document. Replace the title/name above and text below with your own, but keep the headers. Feel free to change the theme and other display settings, although this is not required. I added a new sentence

## Overview {#sec-overview}

Give a brief a description of your project and its goal(s), what data you are using to complete it, and what two faculty/staff in different fields you have spoken to about your project with a brief summary of what you learned from each person. Include a link to your final project GitHub repository.

*I will investigate the impact of different valve procedures on mortality rates among patients with end-stage renal disease (ESRD), while accounting for the competing risk of kidney transplantation. I will clean and filter the Medicare and carrier claim datasets, focusing on patients who have undergone either open-chest aortic or mitral valve replacement (AVR/MVR) or minimally invasive transcatheter aortic valve replacement (TAVR). This analysis aims to utilize logistic regression, survival analysis and competing risk modeling to identify the most suitable valve procedure for ESRD patients based on survival outcomes.*

## Introduction {#sec-introduction}

Describe the problem addressed, its significance, and some background to motivate the problem. This should extend what is in the @sec-overview.

Explain why your problem is interdisciplinary, what fields can contribute to its understanding, and incorporate background related to what you learned from meeting with faculty/staff.

*Dialysis patients undergoing surgical aortic valve replacement (SAVR) tend to have poor survival outcomes, with median survival rates often reported at two years or less. Due to the high surgical risks associated with dialysis patients, the best choice of prosthesis—whether bioprosthetic (bAVR) or mechanical (mAVR)—remains a subject of debate. The current guidelines from the ACC/AHA do not favor one type of valve over the other but instead recommend that surgeons consider patient-specific factors, including the risks of bleeding and valve deterioration, when selecting a prosthesis. The increasing use of transcatheter aortic valve replacement (TAVR) has further complicated decision-making for dialysis patients. While earlier studies suggested similar survival rates between bAVR and mAVR in dialysis patients, recent research, including the largest meta-analysis to date, provides conflicting results. Additionally, there is variability in the reported risks of bleeding, reoperation, and stroke. Regarding the comparison of TAVR versus SAVR for dialysis patients, limited research has been conducted in this high-risk group. As such, these inconsistencies and uncertainties necessitate further exploration. This study aims to compare the outcomes of different prosthesis options for isolated de novo aortic valve replacement in dialysis patients, using a large, up-to-date review of Medicare data.*

*The problem of selecting the optimal prosthesis for dialysis patients undergoing aortic valve replacement using statistical model is inherently interdisciplinary, involving medicine, surgery, biostatistics, and health economics. Cardiologists provide insights into the cardiovascular and renal challenges these patients face clinically, while biostatisticians analyze large datasets, such as Medicare and claims data, to evaluate outcomes retrospectively and inform clinical decisions. During meetings with Dr. Waseem Lutfi and faculty from Cardiology, I gained valuable perspectives on how various factors influence prosthesis selection and kidney transplant wait times. Additionally, discussions with Dr. Jesse Y. Hsu helped me gain expertise in data cleaning, as well as refining the model settings for survival analysis and competing risks modeling. This collaboration across disciplines is essential to understanding the complex decision-making process for dialysis patients.*

## Methods {#sec-methods}

Describe the data used and general methodological approach used to address the problem described in the @sec-introduction. Subsequently, incorporate full R code necessary to retrieve and clean data, and perform analysis. Be sure to include a description of code so that others (including your future self) can understand what you are doing and why.

## Results {#sec-results}

Describe your results and include relevant tables, plots, and code/comments used to obtain them. You may refer to the @sec-methods as needed. End with a brief conclusion of your findings related to the question you set out to address. You can include references if you'd like, but this is not required.

## Conclusion

This the conclusion. The @sec-results can be invoked here.
